---
on:
    push:
        branches:
            - main

jobs:
    deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: 'Az CLI login'
              uses: azure/login@v2
              with:
                client-id: ${{ env.AZURE_CLIENT_ID }}
                tenant-id: ${{ env.AZURE_TENANT_ID }}
                subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
            - name: Deploy
              run: az stack sub create \
                --name graphql-cx \
                --template-file infra/subscription.bicep \
                --deny-settings-mode denyWriteAndDelete
